title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: "https://lukebair.github.io" # Root URL for the site
baseurl: "/hiero-tck-docs" # The repository name (if hosted in a subdirectory)

